version: '3'
 
services:
  space:
    environment:
      - HOST_NAME="https://space.automateyournetwork.ca"
    container_name: space
    restart: always
    image: johncapobianco/space:space
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    # volumes:
    #   - /etc/letsencrypt/archive/space.automateyournetwork.ca/:/etc/letsencrypt/live/space.automateyournetwork.ca/
    networks:
      - all-plugins-nginx-proxy_app_network

  db:
    image: 'postgres'
    environment:
      - POSTGRES_USER=space
      - POSTGRES_PASSWORD=space
      - POSTGRES_DB=space
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: -p 5432
    networks:
      - all-plugins-nginx-proxy_app_network
      
volumes:
  pgadmin:
    driver: local

networks:
  all-plugins-nginx-proxy_app_network:
    external: true
    driver: bridge
  