version: '3'
 
services:
  space:
    image: johncapobianco/space:space
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    # volumes:
    #   - /etc/letsencrypt/archive/space.automateyournetwork.ca/:/etc/letsencrypt/live/space.automateyournetwork.ca/

  db:
    image: 'postgres'
    environment:
      - POSTGRES_USER=space
      - POSTGRES_PASSWORD=space
      - POSTGRES_DB=space
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgadmin:
    driver: local